apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tink
  # namespace: default
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: tink-nginx
  rules:
    - host: tink.com
      http:
        paths:
          - backend:
              service:
                name: console
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: files
                port:
                  number: 8004
            path: /files
            pathType: Prefix
          - backend:
              service:
                name: tink
                port:
                  number: 8003
            path: /tink
            pathType: Prefix
          - backend:
              service:
                name: analysis
                port:
                  number: 8005
            path: /analysis
            pathType: Prefix
