name: test
on:
  push:
    branches:
      - master
      - main
      - release-*
  pull_request:
    branches:
      - master
      - main
      - release-*
jobs:
  test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: .github/workflows/kind/kind.yaml

      - name: add chartrepo
        run: |
          helm repo add tink https://ante-involutum.github.io/chartrepo/
          helm repo update tink

      - name: install
        run: |
          helm install middleware tink/middleware
          helm install console tink/console
          helm install files tink/files
          helm install tink tink/tink
          helm install analysis tink/analysis
          helm install demo tink/demo
